[build]
    publish = "dist"
    command = "pnpm build"
    functions = "functions"
[[redirects]]
    from = "/api/*"
    status = 200
    to = "/.netlify/functions/api/:splat"
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200